using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace backend_api_dotnet9.Migrations;

public partial class AddProductAvatarAndGalleryImages : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("ALTER TABLE products ADD COLUMN IF NOT EXISTS avatar_image_url character varying(1000);");

        migrationBuilder.Sql(@"
            CREATE TABLE IF NOT EXISTS product_images (
                id integer GENERATED BY DEFAULT AS IDENTITY,
                product_id integer NOT NULL,
                image_type character varying(20) NOT NULL,
                image_url character varying(1000) NOT NULL,
                display_order integer NOT NULL DEFAULT 0,
                created_at_utc timestamp with time zone NOT NULL DEFAULT now(),
                CONSTRAINT pk_product_images PRIMARY KEY (id),
                CONSTRAINT fk_product_images_products_product_id FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE
            );");

        migrationBuilder.Sql(@"
            CREATE INDEX IF NOT EXISTS ix_product_images_product_id
            ON product_images (product_id);");

        migrationBuilder.Sql(@"
            CREATE INDEX IF NOT EXISTS ix_product_images_product_id_display_order
            ON product_images (product_id, display_order);");
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("DROP TABLE IF EXISTS product_images;");
        migrationBuilder.Sql("ALTER TABLE products DROP COLUMN IF EXISTS avatar_image_url;");
    }
}
